/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudioVideoRouteImport } from './routes/audio-video'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as NhomHocRouteImport } from './routes/nhom-hoc'
import { Route as ThuVienPaperRouteImport } from './routes/thu-vien-paper'
import { Route as ThuVienPaperIndexRouteImport } from './routes/thu-vien-paper.index'
import { Route as ThuVienPaperSlugRouteImport } from './routes/thu-vien-paper.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioVideoRoute = AudioVideoRouteImport.update({
  id: '/audio-video',
  path: '/audio-video',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const NhomHocRoute = NhomHocRouteImport.update({
  id: '/nhom-hoc',
  path: '/nhom-hoc',
  getParentRoute: () => rootRouteImport,
} as any)
const ThuVienPaperRoute = ThuVienPaperRouteImport.update({
  id: '/thu-vien-paper',
  path: '/thu-vien-paper',
  getParentRoute: () => rootRouteImport,
} as any)
const ThuVienPaperIndexRoute = ThuVienPaperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThuVienPaperRoute,
} as any)
const ThuVienPaperSlugRoute = ThuVienPaperSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ThuVienPaperRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio-video': typeof AudioVideoRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/nhom-hoc': typeof NhomHocRoute
  '/thu-vien-paper': typeof ThuVienPaperRouteWithChildren
  '/thu-vien-paper/$slug': typeof ThuVienPaperSlugRoute
  '/thu-vien-paper/': typeof ThuVienPaperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio-video': typeof AudioVideoRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/nhom-hoc': typeof NhomHocRoute
  '/thu-vien-paper/$slug': typeof ThuVienPaperSlugRoute
  '/thu-vien-paper': typeof ThuVienPaperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio-video': typeof AudioVideoRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/nhom-hoc': typeof NhomHocRoute
  '/thu-vien-paper': typeof ThuVienPaperRouteWithChildren
  '/thu-vien-paper/$slug': typeof ThuVienPaperSlugRoute
  '/thu-vien-paper/': typeof ThuVienPaperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio-video'
    | '/gioi-thieu'
    | '/lien-he'
    | '/nhom-hoc'
    | '/thu-vien-paper'
    | '/thu-vien-paper/$slug'
    | '/thu-vien-paper/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio-video'
    | '/gioi-thieu'
    | '/lien-he'
    | '/nhom-hoc'
    | '/thu-vien-paper/$slug'
    | '/thu-vien-paper'
  id:
    | '__root__'
    | '/'
    | '/audio-video'
    | '/gioi-thieu'
    | '/lien-he'
    | '/nhom-hoc'
    | '/thu-vien-paper'
    | '/thu-vien-paper/$slug'
    | '/thu-vien-paper/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioVideoRoute: typeof AudioVideoRoute
  GioiThieuRoute: typeof GioiThieuRoute
  LienHeRoute: typeof LienHeRoute
  NhomHocRoute: typeof NhomHocRoute
  ThuVienPaperRoute: typeof ThuVienPaperRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-video': {
      id: '/audio-video'
      path: '/audio-video'
      fullPath: '/audio-video'
      preLoaderRoute: typeof AudioVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nhom-hoc': {
      id: '/nhom-hoc'
      path: '/nhom-hoc'
      fullPath: '/nhom-hoc'
      preLoaderRoute: typeof NhomHocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thu-vien-paper': {
      id: '/thu-vien-paper'
      path: '/thu-vien-paper'
      fullPath: '/thu-vien-paper'
      preLoaderRoute: typeof ThuVienPaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thu-vien-paper/': {
      id: '/thu-vien-paper/'
      path: '/'
      fullPath: '/thu-vien-paper/'
      preLoaderRoute: typeof ThuVienPaperIndexRouteImport
      parentRoute: typeof ThuVienPaperRoute
    }
    '/thu-vien-paper/$slug': {
      id: '/thu-vien-paper/$slug'
      path: '/$slug'
      fullPath: '/thu-vien-paper/$slug'
      preLoaderRoute: typeof ThuVienPaperSlugRouteImport
      parentRoute: typeof ThuVienPaperRoute
    }
  }
}

interface ThuVienPaperRouteChildren {
  ThuVienPaperSlugRoute: typeof ThuVienPaperSlugRoute
  ThuVienPaperIndexRoute: typeof ThuVienPaperIndexRoute
}

const ThuVienPaperRouteChildren: ThuVienPaperRouteChildren = {
  ThuVienPaperSlugRoute: ThuVienPaperSlugRoute,
  ThuVienPaperIndexRoute: ThuVienPaperIndexRoute,
}

const ThuVienPaperRouteWithChildren = ThuVienPaperRoute._addFileChildren(
  ThuVienPaperRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioVideoRoute: AudioVideoRoute,
  GioiThieuRoute: GioiThieuRoute,
  LienHeRoute: LienHeRoute,
  NhomHocRoute: NhomHocRoute,
  ThuVienPaperRoute: ThuVienPaperRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
